# Generated by Django 5.1.1 on 2024-11-13 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chatmessage_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['-lastupdated']},
        ),
        migrations.AddField(
            model_name='chat',
            name='lastupdated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
